version: '3'
services:
  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:latest
    networks:
        - clickhouse
    ulimits:
        nofile:
          soft: 262144
          hard: 262144
    ports:
      - "8123:8123"
    volumes:
      - "clickhouse-data:/var/lib/clickhouse"
volumes:
  clickhouse-data:
networks:
    clickhouse:
